In [2]:
import numpy as np

In [ ]:
#np
arr = np.array([1,2,30])

In [ ]:
arr

array([ 1,  2, 30])

In [ ]:
a2darr = np.array([[1,2,3],
                  [4,5,6],
                   [7,8,9]])

In [ ]:
a2darr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a3darr  =np.array([
                    [[1,2,3],
                    [4,5,6],
                    [7,8,9]],

                    [[1,2,3],
                    [4,5,6],
                    [7,8,9]]
                    ])

In [ ]:
arr[1]

np.int64(2)

In [ ]:
a2darr[:,2]

array([3, 6, 9])

In [ ]:
a3darr[1,:,:] # layer , row , column

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# ndim, shape, size, and dtype
a3darr.ndim

3

In [ ]:
a3darr.shape

(2, 3, 3)

In [ ]:
a3darr.size

18

In [ ]:
a2darr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,"ashw",30])


In [ ]:
arr.dtype

dtype('<U21')

### np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()**bold text**

In [ ]:
a1 =np.zeros(3)

In [ ]:
a1

array([0., 0., 0.])

In [ ]:
a2=np.ones(3)
a2

array([1., 1., 1.])

In [ ]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(2,9,2)


array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.ones(2, dtype=np.int64)

array([1, 1])

In [4]:
# Level 1
# Create an array from 1–100.
# Extract all even numbers.
# Extract all numbers divisible by 5.
# Reverse an array.
# Reshape 1–36 into 6 × 6.
# Find row/column sums.
# Find row/column maximums.
# Replace values > 50 with 0.
# Find unique values and frequencies.
# Find mean, median and standard deviation.

arr= np.arange(1,100)
print(arr[arr%2 == 0])
print(arr[arr%5 ==0])
print(np.flip(arr))


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


In [6]:
a2 = np.arange(1,37).reshape(6,6)
print(a2)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [7]:
np.sum(a2,axis= 0)

array([ 96, 102, 108, 114, 120, 126])

In [8]:
# next 3 are similar

In [14]:
arr[arr>50]=0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0]


In [15]:
np.unique(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
np.unique_counts(arr)

UniqueCountsResult(values=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]), counts=array([49,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]))

In [21]:
print(np.mean(arr),"\n",
np.median(arr),"\n",
np.std(arr))

12.878787878787879 
 1.0 
 16.362233385422815
